site_name: MyPythonModule
nav:
    - Home: index.md
    - advanced: advanced.md
    - algorithm: algorithm.md
    - basic: basic.md
    - helper: helper.md
    - math: math.md
    - common: common.md
    - crawler: crawler.md
    - encoding: encoding.md
    - encrypt: encrypt.md
    - run_as_admin: run_as_admin.md
    - unique_key: unique_key.md
    - winreg: winreg.md
    - zhnumber: zhnumber.md
    - zhouyi: zhouyi.md


theme: readthedocs